name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Boost
        run: sudo apt-get install libboost-all-dev
      - name: create Build Dir
        run: mkdir build
      - name: Configure CMake
        working-directory: ${{github.workspace}}/build
        run: cmake ..
      - name: Build
        run: cmake --build build && bash ./rebuild-libs.sh && ./bin/aflat build
      - name: Test
        working-directory: ${{github.workspace}}/bin
        run: ./test 

  check-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install clang-format with npm
        run: npm install -g clang-format
      - name: Check code formatting
        working-directory: ${{github.workspace}}
        run: |
          find . -path ./Lib -prune -o -path ./test/catch.hpp -prune -o -regex '.*\.\(cpp\|hpp\)' -exec clang-format -style=file -i {} \+ -exec git add {} \+
          git diff --cached --exit-code
