name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: create Build Dir
        run: mkdir build
      - name: Configure CMake
        working-directory: ${{github.workspace}}/build
        run: cmake ..
      - name: Build
        run: cmake --build build && bash ./rebuild-libs.sh && ./bin/aflat build
      - name: Test
        working-directory: ${{github.workspace}}/bin
        run: ./test 

  check-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install clang-format
        run: sudo apt-get install -y clang-format
      - name: Check code formatting
        run: |
          find . -regex '.*\.\(cpp\|hpp\|c\|h\)' -exec clang-format -style=file -i {} \+
          git diff --exit-code
